### ISSUE TITLE
show "mount.nfs no such device"

### ISSUE THREAD

**Issue by csskysea** [chaos/netroot#5]
I encounter a problem when boot from pxe.
as screenshot
![image](https://cloud.githubusercontent.com/assets/3860974/15733398/671aef30-283a-11e6-86e7-c047f419787b.png)

pxe server: rhel6.5
boot rootfs:centos 7
installed netroot in boot rootfs

my configration in default file:
label test
menu default
kernel images/vmlinuz-3.10.0-327.18.2.el7.x86_64
append initrd=images/initramfs-3.10.0-327.18.2.el7.x86_64.img root=nfs:192.168.88.1:/images/test rw drm_kms_helper.poll=0 rd.shell ipv6.disable=1 ghes.disable=1 pcie_aspm=off

**Comment by garlick** [comment]
Tomorrow I will see if I can find logs of a successful netroot boot and post them for comparison.

Once you are in the debug shell, can you manually NFS mount the root file system?  Did your network finally come up?

It might be useful to see your dhcp config.  Is your network device channel bonded?

**Comment by garlick** [comment]
Is there a missing colon in root= setting before "rw"?

**Comment by csskysea** [comment]
my network come up,but can not manually nfs mount root file system.
as screenshot:
![image](https://cloud.githubusercontent.com/assets/3860974/15734262/a00b9ec2-2842-11e6-866b-5137511369c7.png)

and my dhcp config like this:
![image](https://cloud.githubusercontent.com/assets/3860974/15734298/fce2689c-2842-11e6-99cb-6a5c2aa42987.png)

besides, my environment can boot rootfs of rhel6.6 with nfsroot instaled.

**Comment by csskysea** [comment]
besides, i use the command to generate initramfs:
dracut --add-drivers sunrpc -m "nfs network base kernel-modules  rootfs-block udev-rules biosdevname" initramfs-3.10.0-327.18.2.el7.x86_64.img

need i package other modules into it?

**Comment by csskysea** [comment]
hi Jim,
        i add new comment in github!

regards,

2016-06-01 21:24 GMT-07:00 Jim Garlick notifications@github.com:

**Comment by garlick** [comment]
Hi Victor, so sorry I didn't get time to look while at work today.  Will try again tomorrow.  Maybe @elgeoman might spot something in your config above if he has a moment to look.

**Comment by garlick** [comment]
Here is some info from our site where netroot is working that may be of help.  Note you must enable RedHat stateless.

**dhcp.conf**

```
 host smurf {
        hardware ethernet 98:88:EE:00:DE:F1;
        fixed-address 192.168.20.20;
        option host-name "smurf";
        filename "pxelinux.0";
                option root-path "nfs4:192.168.20.1:/images/smurf.x86_64,tcp,nocto,retrans=5,soft,nosharecache,acdirmin=600,acregmin=600";
                option pxelinux.pathprefix "/smurf.x86_64/boot/";
                option pxelinux.configfile "pxelinux.cfg";
```

**pxelinux.cfg**

```
label linux
   kernel vmlinuz
   append initrd=initramfs root=dhcp console=tty0 console=ttyS0,115200n8 crashkernel=128M
```

**other notes**
- configure stateless in `/etc/sysconfig/readonly-root` and `/etc/rwtab`
- `netroot-rebuild` is called to build the initramfs
- we are using nfsv4 and selinux (possibly not relevant except for root-path line above)

**Comment by csskysea** [comment]
Hi Jim,
thanks for your support, my environment is OK now, I will continue to pay
attention to the project.

regards,

Victor.C

2016-06-03 9:54 GMT-07:00 Jim Garlick notifications@github.com:

**Comment by csskysea** [comment]
Hi Jim,
can you tell me your pxe server is which distribution?

if i boot netroot from pxe server rhel7,it has no problem,
if i boot netroot from pxe server rhel6.5, about fifteen minutes later
after login, it will have kernel panic.
as screenshot

​

2016-06-05 20:08 GMT-07:00 Chan Victor csskysea@gmail.com:

**Comment by garlick** [comment]
Our systems that run netroot are rhel 7.2 based, both client and server.  Hmm, seems unusual that there would be much relationship between preboot environment and later kernel panic though.

**Comment by csskysea** [comment]
if you have time, you can also test in pxe server based on rhel 6.5, and
tell me your result.

thank you

2016-06-07 20:24 GMT-07:00 Jim Garlick notifications@github.com:

**Comment by csskysea** [comment]
by the way, if netroot can be applied in rhel 6? i mean use netroot-rebuild
to build initramfs for rhel6, rootfs is also rhel6.

2016-06-07 21:38 GMT-07:00 Chan Victor csskysea@gmail.com:

**Comment by garlick** [comment]
> by the way, if netroot can be applied in rhel 6? i mean use netroot-rebuild
> to build initramfs for rhel6, rootfs is also rhel6.

We haven't tried it, but if I remember correctly, we tried to make "stateless" support work in early rhel6 and it didn't quite work for us.   "netroot" depends on stateless working, while "nfsroot" does not, and so I would suggest using only nfsroot on rhel6 systems.

We generally don't mix OS's in clusters (server and clients are the same) but we do have at least one test system that has rhel 6 server and a few nodes converted to rhel 7 for user early access.   The rhel 7 root image was likely built on a rhel 7 system and brought over though (so no chance of contamination of rhel 7 root with bits from rhel 6 server, including pxelinux.0)

**Comment by garlick** [comment]
I will go ahead and close this issue since I think you've made it past the problem it was originally opened for.  Please do feel free to open more issues as things come up.  Regards --Jim

**Comment by csskysea** [comment]
ok ,thanks , BTW, if i can use 9nbd to replace nfs currently?

2016-06-08 12:04 GMT-07:00 Jim Garlick notifications@github.com:

**Comment by garlick** [comment]
Yes it should work.

**Comment by csskysea** [comment]
Hi Jim,
I want to know from which kernel begin to support 9nbd? my current kernel
version is 3.10.0-327.18.2, need i re comile and updae kernel?
i have make 9nbd source code, and get  9nbd.ko, then run "insmod
9nbd.ko",it shows "insmod: ERROR: could not insert module 9nbd.ko: Unknown
symbol in module"

regards,

2016-06-13 21:20 GMT+08:00 Jim Garlick notifications@github.com:

**Comment by garlick** [comment]
What is the unknown symbol?
I last built with a the 7.2 kernel I think.  Will check exactly which.

On Jun 28, 2016 6:48 PM, "csskysea" notifications@github.com wrote:

Hi Jim,
I want to know from which kernel begin to support 9nbd? my current kernel
version is 3.10.0-327.18.2, need i re comile and updae kernel?
i have make 9nbd source code, and get 9nbd.ko, then run "insmod
9nbd.ko",it shows "insmod: ERROR: could not insert module 9nbd.ko: Unknown
symbol in module"

regards,

2016-06-13 21:20 GMT+08:00 Jim Garlick notifications@github.com:

> Yes it should work.
> 
> —
> You are receiving this because you authored the thread.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/chaos/netroot/issues/5#issuecomment-225578307, or
> mute
> the thread
> <
> https://github.com/notifications/unsubscribe/ADrp7iy2MVqKknqaqw8TMnp54H8DAlrBks5qLVkdgaJpZM4IsLo0
> 
> .

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
https://github.com/chaos/netroot/issues/5#issuecomment-229234782, or mute
the thread
https://github.com/notifications/unsubscribe/AAKX2x6nOIpx_FlF_1ddeKu4VPlcn1Qpks5qQc75gaJpZM4IsLo0
.

**Comment by csskysea** [comment]
hi jim,
       "unknown symbol" string is os report.

2016-06-28 21:13 GMT-07:00 Jim Garlick notifications@github.com:

> What is the unknown symbol?
> I last built with a the 7.2 kernel I think. Will check exactly which.
>
